replicaCount: 3

fullnameOverride: notejam
nameOverride: notejam

image:
  repository: TODO
  tag: latest

secrets:
  default:
    enabled: true
    mountPath: /config

deployment:
  enabled: true
  affinity:
    affinityRule: "ShouldBeOnDifferentNode"

service:
  enabled: true
  type: ClusterIP
  ports:
    http:
      internal: 8080
      external: 8080

# ingress:
#   default:
#     enabled: true
#     port: http
#     hosts:
#      "TODO": /
#      "www.TODO": /
#     tls:
#     - secretName: server-tls
#      hosts:
#      - TODO